#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "mips-linux-uclibc-gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DB_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall "
  #define PLATFORM "linux-elf"
  #define DATE "Fri Nov 20 11:42:51 HKT 2015"
#endif
